config:
    security:
        cors:
            allowedOrigin: http://localhost:8082
        enabled: true

env: local
logging:
    level:
        org:
            hibernate: warn
server:
    port: 8891
spring:
    profiles:
        active: default
    application:
        name: Kudos-service
api:
    version: v2


version: '@parent.version@'

azure:
    cosmosdb:
        uri: https://kudos-cosmosdb-ftjvauykldrqe.documents.azure.com:443/
        key: p6eeE4yjYaJzb8mq38cwVbpXfAX6yXSxqXdu3gMofeJWbkm05wSJNGSMNWYYaohq1g5ruZCCzS1K6k9yZeZtug==
        database: kudos
        consistency-level: session
        allow-telemetry: true
    application-insights:
        instrumentation-key: 9fc0202d-7bd3-4a1d-b9e4-a80d378a876eapp

#  eventgrid:
#    keyname: aeg-sas-key
#    keypass: vXa6bU5zc+pDYV/6tYBST/a0lofPLMXQDQ6PLRPlnvU=
#    uri: https://inca-event-grid.westeurope-1.eventgrid.azure.net/api/events?api-version=2018-01-01
#  search:
#    uri: https://incacsas.search.windows.net/indexes/inca-test-documentdb-index/docs?api-version=2017-11-11-Preview&searchFields=firstname,surname,usernumber&queryType=full&top=30&search=
#    keyname: api-key
#    keypass: 33BB541C0B59D66D07C2101D002F605A
