spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  security:
      cors:
          allowedOrigin: ${ALLOWED_ORIGINS}
          enabled: true
logging:
    level:
        org:
            hibernate: warn
server:
    port: 8891

version: '@parent.version@'

api:
    version: v2

azure:
    cosmosdb:
        uri: "#{systemEnvironment['COSMOS_URI']?:'**'}"
        key: "#{systemEnvironment['COSMOS_KEY']?:'**'}"
        database: "#{systemEnvironment['COSMOS_DB_NAME']?:'**'}"
        consistency-level: session
        allow-telemetry: true
    application-insights:
        instrumentation-key: "#{systemEnvironment['APP_INSIGHTS_KEY']?:'**'}"

