apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionLimit }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          env:
            - name: SP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-sp-client
                  key: azure.keyvault.client-id
            - name: SP_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-sp-client
                  key: azure.keyvault.client-key
            - name: SPRING-PROFILES-ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: user-service
                  key: spring.profiles.active
            - name: IMPORT-ORGANIZATION-CRON
              valueFrom:
                configMapKeyRef:
                  name: user-service
                  key: import.organization.cron
            - name: IMPORT-ORGANIZATION-EMAIL-OVERWRITE
              valueFrom:
                configMapKeyRef:
                  name: user-service
                  key: import.organization.email.overwrite
            - name: IMPORT-ORGANIZATION-EMAIL-ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: user-service
                  key: import.organization.email.address
            - name: ALLOWED-ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: user-service
                  key: allowedOrigins
            - name: DB-USERS-URL
              valueFrom:
                configMapKeyRef:
                  name: user-service
                  key: db.users.url
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
